version: '3.3'

services:

  server:
    image: jigen
    networks:
      - root
      - app
    environment:
      # - MONGO_USER=admin
      # - MONGO_PASS=admin
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - NODE_ENV=production
      - JWT_SECRET=MY_PRIVATE_SECRET
      - PORT=4000
      - SERVICE_PORTS=4000
      - VIRTUAL_HOST_WEIGHT=1
      - VIRTUAL_HOST=https://robbot.ir,http://robbot.ir
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

networks:
  root:
    external:
      name: root
  app:
    external:
      name: app