name: Deploy

on:
  push:
    branches:
    - release

jobs:
  deploy:
    runs-on: [self-hosted, release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Node version
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: yarn
    - name: Start PM2
      run: |
        pm2 delete back-end | true
        pm2 start npm --name back-end -- run start:src